name: saas_k8s

networks:
  pdns:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

volumes:
  caddy_data:
  caddy_config:
  mariadb:
  pdns-data:

services:
  # step-ca:
  #   image: smallstep/step-ca:latest
  #   container_name: step-ca
  #   networks:
  #     pdns:
  #       ipv4_address: 172.30.0.22
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./_data/step-ca:/home/step
  #   restart: always

  # mariadb:
  #   container_name: pdns-mariadb
  #   image: mariadb:lts-ubi
  #   networks:
  #     pdns:
  #       aliases:
  #         - db
  #         - mysql
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - mariadb:/var/lib/mysql:Z
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=my-secret-pw
  #   healthcheck:
  #     test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
  #     timeout: 10s
  #     retries: 5
  #   restart: always

  # pdns-mysql-master:
  #   image: pschiffe/pdns-mysql:5.0-alpine
  #   container_name: pdns-mysql-master 
  #   hostname: ns1.example.com
  #   networks:
  #     pdns:
  #       ipv4_address: 172.30.0.20
  #       aliases:
  #         - pdns
  #   ports:
  #     # - "53:53/udp"
  #     # - "53:53/tcp"
  #     - "8081:8081" # API for the UI to talk to
  #   extra_hosts:
  #     - 'ns1.saas.test:172.30.0.20'
  #     # - 'ns2.example.com:172.30.0.21'
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - PDNS_gmysql_password=my-secret-pw
  #     - PDNS_primary=yes
  #     - PDNS_api=yes
  #     - PDNS_api_key=secret
  #     - PDNS_webserver=yes
  #     - PDNS_webserver_address=0.0.0.0
  #     - PDNS_webserver_allow_from=0.0.0.0/0,172.30.0.0/16
  #     - PDNS_log_dns_queries=true
  #     - PDNS_default_ttl=1500
  #     - PDNS_allow_axfr_ips=0.0.0.0/0
  #     - PDNS_only_notify=0.0.0.0/0
  #     - PDNS_dnsupdate=true
  #     - PDNS_allow_dnsupdate_from=0.0.0.0/0
  #   depends_on:
  #     - mariadb
  #   restart: always

  # pdns-recursor:
  #   container_name: pdns-recursor
  #   # image: pschiffe/pdns-recursor:5.3-alpine
  #   image: powerdns/pdns-recursor-53
  #   networks:
  #     pdns:
  #       ipv4_address: 172.30.0.21
  #   ports:
  #     - "53:53/udp"
  #     - "53:53/tcp"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./docker/powerdns/recursor.conf:/etc/powerdns/recursor.conf:ro
  #   environment:
  #     - PDNS_forward_zones.=8.8.8.8
  #   #   - PDNS_local_address=0.0.0.0
  #   #   - PDNS_allow_from=127.0.0.0/8, 172.16.0.0/12, 10.0.0.0/8
  #   #   - PDNS_api_key=secret
  #   #   - PDNS_webserver=yes
  #   #   - PDNS_webserver_address=0.0.0.0
  #   #   - PDNS_webserver_password=secret2
  #   ulimits:
  #     nofile:
  #       soft: 10000
  #       hard: 10000
  #   # depends_on:
  #   #   - pdns-mysql-master
  #   restart: always

  etcd:
    image: quay.io/coreos/etcd:v3.5.7
    container_name: etcd
    network_mode: host
    # networks:
    #   pdns:
    #     ipv4_address: 172.30.0.24
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    restart: always
    # ports:
    #   - "2379:2379"
    #   - "2380:2380"

  coredns:
    image: coredns/coredns
    container_name: coredns
    network_mode: host
    # networks:
    #   pdns:
    #     ipv4_address: 172.30.0.25
    # ports:
    #   - 53:53/udp
    #   - 53:53/tcp
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./docker/coredns:/etc/coredns
    environment:
      - GOMAXPROCS=8
    restart: always
    depends_on:
      - etcd

  # netshoot:
  #   image: nicolaka/netshoot:latest
  #   container_name: netshoot
  #   command: sleep 3600
  #   networks:
  #     pdns:
  #       ipv4_address: 172.30.0.50
  #   dns: 172.30.0.25
  #   restart: always
  #   depends_on:
  #     - coredns

  # bind:
  #   image: ventz/bind
  #   container_name: bind
  #   restart: unless-stopped
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #   volumes:
  #     - ./docker/bind/etc/bind:/etc/bind

  # caddy:
  #   image: caddy:2.10.2
  #   container_name: caddy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
  #     - ./certs:/certs # your pre-generated existing TLS certs
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   restart: always
