site_name: Saas Data Platform on Kubernetes

nav:
  - Home: index.md
  - Features:
      - features/overview.md
  - Deployments:
      - Overview: deployments/index.md
      - deployments/k3s.md

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
