apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: workspaces.platform.saas.test
spec:
  group: platform.saas.test
  names:
    kind: Workspace
    plural: workspaces
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                extWorkspaceId:
                  description: External workspace ID
                  type: string
                bootstrapToken:
                  description: Workspace bootstrap token
                  type: string
              required:
                - extWorkspaceId
                - bootstrapToken
