apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: jupyterhub
  namespace: crossplane-system
spec:
  compositeTypeRef:
    apiVersion: platform.saas.test/v1alpha1
    kind: Jupyterhub
  mode: Pipeline
  pipeline:
    - step: deploy
      functionRef:
        name: function-workspaceapps
      requirements:
        requiredResources:
        - requirementName: workspace-bootstrap-secret
          apiVersion: v1
          kind: Secret
          name: app-configuration
          namespace: default