# sa-secret-generator.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevela-addon-task-sa
  namespace: vela-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: saas-workload
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer-binding
  namespace: saas-workload
subjects:
  - kind: ServiceAccount
    name: kubevela-addon-task-sa
    namespace: vela-system
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
