apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-helm-values
  namespace: vela-system
type: Opaque
stringData:
  values.yaml: |
    # put values.yaml content
    fullnameOverride: "jupyterhub"
    hub:
      db:
        type: postgres
        url: postgresql+psycopg2://jupyterhub@jupyterhub-db-rw.saas-workload.svc.cluster.local:5432/jupyterhub
        password: 47krOr7uzgXpLrdL
