dnssec:
  log_bogus: true
incoming:
  listen:
    - 0.0.0.0
    - 127.0.0.1
    - '[::1]:5353'
    - '::'
  allow_from: [172.0.0.0/8, 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, '::1/128', 'fc00::/7', 'fe80::/10']
recursor:
  extended_resolution_errors: true
  # forward_zones:
    # - zone: example.com
    #   forwarders:
    #     - 127.0.0.1:5301
outgoing:
  source_address:
    - 0.0.0.0
    - '::'
logging:
  loglevel: 6