apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.prefix }}-system
  labels:
    platform.role: system
    platform.protected: "true"
    platform.breakglass: "false"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.prefix }}-workload
  labels:
    platform.role: workload
    platform.protected: "true"
    platform.breakglass: "false"
