events {}

http {
  server {
    listen 80;
    server_name _;

    root /srv/saas;
    index index.yaml;

    location / {
      try_files $uri =404;
    }

    location /charts/ {
      add_header Cache-Control "public, max-age=31536000, immutable";
    }
  }
}
