server {
    listen 443 ssl;
    server_name test.internal;

    ssl_certificate     /etc/nginx/certs/*.internal.pem;
    ssl_certificate_key /etc/nginx/certs/*.internal-key.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
